image: alpine/edge
packages:
- hut
- nodejs
- npm
- esbuild
oauth: pages.sr.ht/PAGES:RW
tasks:
- test: |
    cd requinto
    npm install
    node --test
- build: |
    cd requinto
    mkdir -p dist
    esbuild script.js --bundle --minify --sourcemap --outfile=dist/bundle.js
    esbuild style.css --bundle --minify --sourcemap --outfile=dist/bundle.css
    sed 's/src="script.js"/src="bundle.js"/; s/href="style.css"/href="bundle.css"/' index.html > dist/index.html
    cp LICENSE dist/LICENSE
- package: |
    cd requinto/dist
    tar -cvz . > ../../website.tar.gz
- upload: |
    hut pages publish --domain requinto.whereis.social website.tar.gz
