image: alpine/edge
packages:
- hut
- nodejs
oauth: pages.sr.ht/PAGES:RW
tasks:
- test: |
    cd requinto
    node --test
- package: |
    cd requinto
    tar -cvz --exclude='.git' --exclude='*.tar.gz' --exclude='.build.yml' --exclude='justfile' --exclude='node_modules' --exclude='package.json' --exclude='package-lock.json' --exclude='*.test.js' . > ../website.tar.gz
- upload: |
    hut pages publish --domain requinto.whereis.social website.tar.gz
